apiVersion: v1
kind: Service
metadata:
  name: angular-ui-dev-service
  namespace: jenkins
spec:
  type: ClusterIP
  selector:
    app: angular-ui-dev
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

